### ISSUE TITLE
$firebase objects should have an $id

### ISSUE THREAD

**Issue by lezhangxyz** [firebase/angularfire#187]
It's sometimes useful to reference an individual item's $id when saving data or for data administration.It's simple to do this with the standard JS Firebase library by using snapshot.name(), but the id doesn't seem to be exposed by $firebase objects. It looks like it would just require setting a variable in the _getInitialValue function.

**Comment by ajbraus** [comment]
+1 I don't understand, the objects themselves don't have id's. You can't even easily create RESTful routing "/projects/:id" without an id attribute. Having the id as the primary identifying attribute of an object is the most universal pattern I've seen in the web. Why abandon it?

**Comment by jamestalmage** [comment]
Years old issue. See the docs referenced above.

**Comment by jwngr** [comment]
@ajbraus - As James said, this is a very old post from two years ago and the API has changed twice in a major way since this issue was created. If you want to carry on a discussion about this, please open a new issue. That being said, every `$firebaseObject` and each item in `$firebaseArray` has an `$id` attribute which specifies the key for the node at which data is stored. We are not shying away from the ID pattern. You can and should use `$id` as your unique identifier.
