### ISSUE TITLE
Multiple $firebase instances attached to same path do not trigger `loaded` event

### ISSUE THREAD

**Issue by katowulf** [firebase/angularfire#194]
When two controllers access the same Firebase path, only the first `$on('loaded', ...)` handler gets fired.

This is due to the fact that locally cached data fires `value` events synchronously in Firebase. So on the first load, the server is contacted asynchronously by angularFire's [_getInitialValue](https://github.com/firebase/angularFire/blob/master/angularfire.js#L258) method.

However, on the second load, since the value is already local, the [broadcast event](https://github.com/firebase/angularFire/blob/master/angularfire.js#L255) happens synchronously, and therefore before your $on('loaded'...) handler gets attached.

See also: http://stackoverflow.com/questions/20768258/on-loaded-fires-once-for-new-references-firebase.

**Comment by apptimise** [comment]
All, I have the same problem in AngularFire `1.2.0`. the @katowulf 's comment wouldn't work, because the `$loaded()` in `obj.$loaded().then(function(values){...})` will not be triggered for the 2nd time, so doesn't matter if you use `obj` or `values`, the `then()` part will never be called. Any other suggestions?
