### ISSUE TITLE
Add $update method to non-destructively modify data

### ISSUE THREAD

**Issue by ncammarata** [firebase/angularfire#238]
It could be that I'm misunderstanding the docs, but it seems like if I have

``` javascript
user = { name: 'nick', github: 'ncammarata' } ($firebase object)
```

and I use

``` javascript
user.$set({ name: 'nick c' });
```

The github property is now gone. 

How would I set and save only a single property? Right now I'm manually `$set`ing and `$save`ing multiple properties, which is tedious.

**Comment by premiumFrye** [comment]
is this anywhere in the docs?

Btw, great talk at ng-conf!

**Comment by jwngr** [comment]
Thanks for the compliment! Glad you are giving AngularFire a try.

This issue is over 14 months old and the API has undergone two large revisions since. You can find the current docs here:
* [Quickstart](https://www.firebase.com/docs/web/libraries/angular/quickstart.html)
* [Guide](https://www.firebase.com/docs/web/libraries/angular/guide)
* [API Reference](https://www.firebase.com/docs/web/libraries/angular/api.html)

**Comment by premiumFrye** [comment]
Thanks for the quick response! At least one of those revisions has happened since I started this side project on nights and weekends months and months ago, so I think it's back to the drawing board.

**Comment by jwngr** [comment]
I think you will find the recently-released 1.0.0 API to be much easier to use! Feel free to open a new issue or post to the [AngularFire Google Group](https://groups.google.com/forum/#!topic/firebase-angular) if you have questions.

**Comment by colindevs** [comment]
@jwngr @anantn I am using Angularfire v1.1.3 and there is no $update() method for $firebaseObjects. Will that be coming soon? It really would help when trying to modify a user account without destroying the whole thing and recreating it!

**Comment by colindevs** [comment]
Or is there any other way to  $save non-destructively?

**Comment by katowulf** [comment]
Not supported. You're probably looking for $firebaseArray.
