### ISSUE TITLE
How do I insert into an array?

### ISSUE THREAD

**Issue by ProLoser** [firebase/angularfire#523]
I've found that the inability to perform things like reverse() or splice() on arrays has rendered the usefulness of firebase to nearly useless.

I need to insert items into the middle of an array. How do you propose I do this? It's completely annoying to expect me to use arrays without this capability. That said, if I were to use an object, how do you propose I retain order?

**Comment by jwngr** [comment]
We've discussed array extensively on our blog ([here](https://www.firebase.com/blog/2014-05-06-synchronized-arrays.html) and [here](https://www.firebase.com/blog/2014-04-28-best-practices-arrays-in-firebase.html)) and in our docs ([here](https://www.firebase.com/docs/web/guide/understanding-data.html)), so give those a read for more details. The gist of the problem with arrays is that they are a terrible data structure for realtime data. If you think about an array, you always are inserting at a certain position or index in the array. If two separate clients insert into array index 3 at the same time, how would you resolve that merge conflict on the server since you can't guarantee the first person who wrote will get there first. That is why we always suggest using something like `push()` to insert into the end of a node and design your code such that it doesn't matter who got there first.

95% of the time that people ask us about arrays in Firebase, they are asking about an [XY problem](http://meta.stackexchange.com/questions/66377/what-is-the-xy-problem). The answer is usually to rethink what they want to do and how they would do it in the Firebase, NoSQL way. What is that way? Well, its hard to answer that without knowing your use case, so sharing what you are attempting to achieve would be very helpful. That being said, it looks like you are just trying to order data so I would suggest using [Firebase queries](https://www.firebase.com/docs/web/guide/retrieving-data.html#section-queries). Each child node of a parent node can have an `order` attribute which specifies its "index." Then, to "insert into the middle of the list" you can add a node with an `order` value which will put it in the position you want. It will still get added to the end of the parent node, but you can get all the children node in order by using this query:

```
$scope.orderedItems = $firebase(ref.child("items").orderBy("order")).$asArray();
```

**Comment by ProLoser** [comment]
Are you then suggesting that were I to inject a new node in the middle I would then have to iterate through all the subsequent siblings and update their `order`? I have considered using an object and simply storing an order as a property, but I need a strong way to be able to inject items in the middle easily and also move items up/down easily.

Also, there is at most only a few individuals editing the same data simultaneously so who's changes go last is not very important. I'm noticing a weird behavior however that if I try updating on `ng-change` or something, and I type to fast, the text will occasionally revert back to a few words prior to what I typed in. Obviously this is a race condition with a response coming back and updating the field i'm in the middle of editing, but I was the only one editing the document to begin with.

This is the project I'm working on: http://proloser.github.io/screenwriter/#/demo

**Comment by jwngr** [comment]
Updating all subsequent siblings is a valid way to solve this problem, but there are others. You could use non-numeric values for `order` which allow you to easily insert between two existing values. Or you could use decimal values to do the same. I know of at least one Firebase user who has implemented a [Dewey decimal](http://en.wikipedia.org/wiki/Dewey_Decimal_Classification)-like system for this exact thing. Again, this is highly dependent on your use case, which is still not clear to me.

As for the overwriting issue you are having with `ng-change`, that sounds like an unrelated issue. If you really think you've found a bug, please create a reduced repro (the link you shared is too complex for us to reasonably debug) and open a new issue. We will take a look.

**Comment by ProLoser** [comment]
Okay, so I've actually been spending the past 3 days rewriting my entire app into ReactJS specifically to tackle this one bug.

See, I hate the idea of using an `order` or `sort` property because it means inserts would require iterating through all of the subsequent siblings and updating their sort property. This is mui mallo.

I realized, for my purposes, a LinkedList is absolutely perfect. Every single item in the collection now contains a `next` property which contains the key of it's immediate sibling. Now if I want to do inserts, I simply have to adjust the pointers of 2 rows and I'm done.

That said, I realize I will probably have to implement this myself, but is there any chance you guys would be willing/interested in implementing a different type of sort query that specifically deals with linkedlist designs? Or have a suggestion on the best way for me to go about doing this myself? I would like to `bindAsArray()` and have that array be sorted using the next property approach.

**Comment by katowulf** [comment]
Thanks for the feedback. Have a great day.
