### ISSUE TITLE
$remove method on $FirebaseObject don't delete object from db

### ISSUE THREAD

**Issue by infernalmaster** [firebase/angularfire#527]
I did like in [doc](https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-firebaseobject-remove). This method returns successful promise, but don't delete object from firebase.

So the code of `$remove` [is](https://github.com/firebase/angularfire/blob/15e76f3a0367966326aa105b7eb1931625303a7e/src/FirebaseObject.js#L88)

        $remove: function() {
          var self = this;
          $firebaseUtils.trimKeys(this, {});
          this.$value = null;
          return self.$inst().$remove(self.$id).then(function(ref) {
            self.$$notify();
            return ref;
          });
        },

Seems problem is in this row

    return self.$inst().$remove(self.$id).then(function(ref) {

So I tried to rewrite it without argument for `$inst().$remove` and it works. So maybe it should be like this

    return self.$inst().$remove().then(function(ref) {

Because there is one interesting line in code [$inst().$remove()](https://github.com/firebase/angularfire/blob/15e76f3a0367966326aa105b7eb1931625303a7e/src/firebase.js#L74)

    if (arguments.length > 0) {
        ref = ref.ref().child(key);
    }

So we need to call `remove` on object but not on his child.

Or maybe everything works but I'm doing something wrong? My code is

        ref = new Firebase("#{fbURL}/posts/#{id}")
        sync = $firebase ref
        sync.$asObject().$remove()

**Comment by jwngr** [comment]
Hey @infernalmaster - could you please provide a working repro (via JSFiddle or CodePen) which shows this issue? This code is pretty heavily tested and we haven't heard of any issues with this method until now. But if you think you've found something, please share a repro with us so we can debug it live. Thanks!

**Comment by infernalmaster** [comment]
So I created public example to show my proble
http://plnkr.co/edit/uoetu9bZuMZFjbwPMOlw?p=preview

**Comment by jwngr** [comment]
I've got a working Plunkr for you [right here](http://plnkr.co/edit/7IS97Y2ue45LF6c5wYcS).

First off, you are using version `v0` of the Firebase client, which is *ancient*. We are two major versions ahead of that library and I'm surprised `v0` even works at all with AngularFire 0.9.1. It is certainly not officially supported by the latest version of AngularFire. My updated Plunkr uses Firebase 2.1.1, which is the latest version as of this comment.

You are making the removal a little overly complex and I was actually able to accomplish what you wanted by removing some code. The gist of the issue here is that you are never actually removing the object from the array you created. Instead of passing in the object-to-remove's ID, creating a new `$FirebaseObject`, and calling `$remove()` on that, all you need to do is pass the object itself:

```
<a href ng-click="removeRecord(user)">Delete</a>
```

and then call `$remove()` on the `$FirebaseArray`:

```
// Remove user   
$scope.removeRecord = function(user) {
  $scope.users.$remove(user).then(function(){
    alert('user removed, and IT IS TRUE :)');
  });
};
```

That should accomplish what you are trying to achieve.

I am looking into if we have an issues with `$remove()` though. I made [a reduced repro](http://plnkr.co/edit/az0b5MxqO4PkyuUDsyGY) which still seems to be acting strangely. @katowulf and I will take a look and track down the issue.

**Comment by jwngr** [comment]
It does look like we do in fact have a bug [here](https://github.com/firebase/angularfire/blob/1197e1b8a39410ddd7452a609b301e24fdaacffb/src/FirebaseObject.js#L88) and our test suite doesn't properly test this case. @katowulf is fixing it up right now (and adding more tests). It will go out with the next 0.9.2 release. Thanks for reporting!

**Comment by infernalmaster** [comment]
It doesn't matter now, but I want to explain some moments. That example was created by other person, so I just changed some moments to show you the problem. So that is why there was old version v0.
And it does not show my real use case. In my app (it's blog) I also have route for single item. So there I load just that one item (without loading whole collection) and I need to delete that just using `item.$remove()`.

**Comment by jwngr** [comment]
Makes sense. This is now fixed in `master` and will go out as AngularFire 0.9.2 soon. Thanks again for reporting this.
