### ISSUE TITLE
Properties on Error are non-enumerable

### ISSUE THREAD

**Issue by katowulf** [firebase/angularfire#529]
Errors returned by Firebase can't be printed to the screen using {{ error }} because the properties are non-enumerable. Maybe we should wrap these in something Angular could understand before rejecting our promises?

**Comment by jwngr** [comment]
:disappointed:

**Comment by jwngr** [comment]
We will consider returning our own error objects that contain just a message, code, and stack.

**Comment by jamestalmage** [comment]
What about doing an (angular filter)[https://docs.angularjs.org/api/ng/filter/filter] so you could print them out with  `{{ error | fb_error }}`

**Comment by jamestalmage** [comment]
I looked into this, and it isn't a Firebase / Angularfire specific issue. `Error`'s properties are not enumerable according to the spec ([V8 team discussion on the topic here](https://code.google.com/p/v8/issues/detail?id=1595)).

I vote close this as `won't fix`. Or alternately write a filter like I suggested above, but my thinking is that it's a general problem not specific to angularfire and would be useful released as a separate lib.

**Comment by jwngr** [comment]
I looked into this a bit myself, and I agree that we should won't fix this one as it is beyond the scope of AngularFire. Thanks for the info @jamestalmage!

**Comment by katowulf** [comment]
I don't really agree with this outcome. While the properties on Error are in fact non-enumerable (that was the title of the issue), and this is indeed a problem that is not specific to AngularFire, it's still one that tripped me up while dogfooding AngularFire. I suspect, therefore, it's going to trip others up while using our lib. If we're going to return error objects in our promises, they should probably be something that can be used in a view.

If you're still not swayed, I can defer here. But I feel like this is going to cost dev time with something we could remedy.

**Comment by jwngr** [comment]
Yeah I'm on the fence on this. I kind of group this with the "async bug trap" issue that people run into with things like `$asArray()` and `$loaded()`. It's annoying, but it's not really our fault per se. It's just JavaScript gotchas. We could throw non-`Error` objects but I actually don't really like that solution since the `Error` object exists for a reason. If anything, Angular should add parsing capabilities so that doing `{{ error }}` actually prints something other than `{}`. AngularFire just seems like the wrong place to fix this quirk.
