### ISSUE TITLE
$watch event types differ between object and array

### ISSUE THREAD

**Issue by dhcar** [firebase/angularfire#535]
Right now every time data changes in an angularfire object watcher it is always passed the event type "value" and the key for this data is the key of the parent, not the child that was effected by the event.

However, angularfire arrays update with the event type and key of the actual event. For instance "child_removed" or "child_added".

Here's a plunker that shows the issue
http://plnkr.co/edit/c6BmU4XoFTubES2KW6bY?p=preview

**Comment by jwngr** [comment]
This is expected behavior. There are no "child_added" or "child_removed" events on `$FirebaseObject`. When you create a `$FirebaseObject`, we create a single listener on that object, not any of its children nodes. So it makes sense that we data changes in a deep child, the parent receives the event. This is expected and intended.
