### ISSUE TITLE
Build failing on master.

### ISSUE THREAD

**Issue by jamestalmage** [firebase/angularfire#552]
See my comments on #541 (unrelated, but I discovered the problem there)

**Comment by katowulf** [comment]
This is a bug/change in jasmine-core equal methods (released yesterday). Works in 2.1.x but not in 2.2.0. We'll investigate this as a low priority fix.

**Comment by jwngr** [comment]
Looking at the [changelog for 2.2.0](https://github.com/jasmine/jasmine/blob/master/release_notes/2.2.0.md) and the [changelog for 2.2.1](https://github.com/jasmine/jasmine/blob/master/release_notes/2.2.1.md), it looks like there were some changes to some Jasmine equality checks. Looking at the newly failing test, the two sides are identical. So there must be a bug in the `jasmine-core` stuff. I'll put a PR together which pins us to the earlier version of `jasmine-core` so that these stop failing.

**Comment by jwngr** [comment]
I think this item from the [`jasmine-core` 2.2.0 changelog](https://github.com/jasmine/jasmine/blob/master/release_notes/2.2.0.md) is the issue:

> Check custom properties on Arrays when computing equality

Fix coming in hot.
