### ISSUE TITLE
$createUser uid is too simple - prevents using uid as a key in firebase

### ISSUE THREAD

**Issue by henry74** [firebase/angularfire#569]
I noticed the uid for Facebook and Google are unique enough where it would be difficult to guess, but simplelogin:1 simplelogin:2 are very easy to guess even though they are unique.  I was hoping to use uid as a way to refer to users, but it introduces security issues if the uid's are too easy to guess.

I'm saving the authData returned to create a user record, but given the ease of guessing a uid, what is a better option?  Use $push and have firebase create keys that way?

Open to suggestions, but a bit bummed I may not be able to use uid directly.

**Comment by katowulf** [comment]
Henry, thanks for reaching out. $createUser() simply wraps the SDK method, so this isn't a complaint with AngularFire, but rather with the Firebase SDK. I'll ping the auth team and add your thoughts here to the feature discussion.

**Comment by jwngr** [comment]
> I was hoping to use `uid` as a way to refer to users, but it introduces security issues if the `uid`s are too easy to guess.

This is not true. There are no security issues with a guessable `uid`. The `uid`s for Facebook, Twitter, etc. are also guessable since they are just `<provider>:<providerId>` where `<providerId>` is your public Facebook ID, Twitter ID, etc.

Firebase authentication will generate a Firebase authentication token on our servers which is signed with your secret. The payload of this token is what is put in the [`auth` variable](https://www.firebase.com/docs/security/api/rule/auth.html) in your Security Rules. The only way to generate this token is to first authenticate with the proper credentials. There is no way to spoof the Firebase authentication token client-side even if you know the user's `uid`. In order to do that, you would need the Firebase secret. But if you have that, then you already have the keys to the kingdom.

What you need is our [user-based security rules](https://www.firebase.com/docs/security/guide/user-security.html). You should actually probably give [the whole security guide](https://www.firebase.com/docs/security/guide) a read to understand how Firebase security works. For example, you can make it so that they any authenticated user can read other user's data but only write to their own user data with rules like these:

```
{
  "rules": {
    "users": {
      ".read": "auth !== null",
      "$uid": {
        ".write": "auth.uid === $uid",
      }
    }
  }
}
```

Ultimately, there is nothing to pass on to the auth team here since there are no security issues around this issue. When dealing with user sign-on, it is important to differentiate authentication vs identification. Just because it is easy to guess identification does not mean it is easy to spoof authentication. That is what is happening in this case.

**Comment by henry74** [comment]
Here's a potential scenario which wouldn't be all that uncommon.  Assume uid is used through an application to retrieve a user's profile.  If the uid is passed as a parameter to retrieve a user's detail - it's possible for another "authenticated" user to change a URL to retrieve another user's detail assuming a user can read another user's data.  The Firebase example shows saving authData as the user's data using the uid as the key in the collection which implies using that key (since it's unique) is quite acceptable.

I appreciate the tutorial on firebase security rules, but this is really about being able to simply increment the simplelogin:# uid into a valid uid for another user.  All keys are "guessable" but so are all passwords (eventually).

**Comment by katowulf** [comment]
Security rules should be used to secure data access, not obscurity. If the user has read access to the data, then reading it should not be a problem. You can certainly prevent them from writing to another profile.

**Comment by henry74** [comment]
It's certainly a matter of opinion but I can think of many cases where obscurity is just fine - for example an order # from an online store or a tracking # from UPS.  Hey, why don't credit cards just increment their numbers if they have a security key on the back? 

Having a "unique" key that's basically a prefix followed by an incremented number is poor design choice as a generated key when so many other options exist which are just as easy, yet much more random.  So an email authentication returns a uid, but it's simple generation makes it a poor match to use a user key for an application due it's simplicity.

Obscurity, like anything security related, is used with other mechanisms like 2-factor authentication or physical keys to make it less easy for a system to be compromised.

Anyways - I was offering it as an enhancement suggestion.  Ignore if you want.  It's poor design, but that's just one person's opinion :-)

**Comment by katowulf** [comment]
Thanks again for the feedback. As I mentioned before, I've put your vote on the list for discussion with the team. We certainly appreciate your thoughts here. It's devs that take the time to offer feedback--like you!--who make the Firebase community so amazing and fun.
