### ISSUE TITLE
404 error for the 1.0.0 migration guide

### ISSUE THREAD

**Issue by liamtarpey** [firebase/angularfire#575]
I've been presented with this console error '$firebase has been removed' with the latest release of AngularFire. Upon following the link to the migration guide I'm getting a [404 error](https://www.firebase.com/docs/web/libraries/angular/guide/migration-guides.html).

Unforunately it doesn't look like [the docs](https://www.firebase.com/docs/web/libraries/angular/quickstart.html) have been updated either as they still suggest to register firebase in the app as such:

var app = angular.module("sampleApp", ["firebase"]);

Thank you.

**Comment by jwngr** [comment]
Sorry you are running into issues. We did a soft launch of AngularFire 1.0.0 yesterday and are waiting until later today to officially announce it at ng-conf. So that is why the docs aren't there yet! Check back later today and everything will be there. You really are at the edge of this technology!

**Comment by jwngr** [comment]
This is now fixed.

**Comment by liamtarpey** [comment]
Thank you so much Jacob! I think the timings were completely accidental! :)
