### ISSUE TITLE
Test units don't exercise browserify

### ISSUE THREAD

**Issue by katowulf** [firebase/angularfire#585]
No tests to ensure we work with browserify. Maybe add an e2e? See #584

**Comment by jwngr** [comment]
I'm not so bullish on this idea. I don't really know what this test would look like and I don't think it adds a whole lot of value. I vote we close this.

**Comment by katowulf** [comment]
Shh, if @bendrucker hears you, there'll be no end to the frowny faces you receive. Ben: Any advice on an easy approach to making sure we don't break browserify in future releases, without making Jacob sad?

**Comment by bendrucker** [comment]
Love that I'm building a reputation as the Browserify police :police_car: :rotating_light: 

The problem here is that master doesn't represent a valid CommonJS package. Only the tagged builds with the `dist/` dir do. 

The issue in which you referenced this isn't related to Browserify either.

The only way to break Browserify usage would be by renaming or restructuring the build or renaming the module. I'd recommend using Browserify to do the build process and write the tests though, which would technically cover this and eliminate the need for an intermediate broken state on master.
