### ISSUE TITLE
$update deprecated

### ISSUE THREAD

**Issue by premiumFrye** [firebase/angularfire#593]
Btw, first time issue-filer, long time user--thanks: glad to be here. Sorry if I'm tripping over any protocols or if I'm missing something. 

Anyway, looks like when the `$firebase` service was removed in [6e38dad8f976ab42496b9818cae1ffd1a257db71](https://github.com/firebase/angularfire/commit/6e38dad8f976ab42496b9818cae1ffd1a257db71) the `$update` method was removed along with it (not migrated to `$firebaseObject`).  I understand `$firebaseObject` is not a drop-in replacement for `$firebase`, it was still frustrating when I could find any mention of that feature's deprecration (unless I'm totally missing something).

Can `$update()` be added `$firebaseObject`, analogulously to `$firebaseArray.$add()`? Seems like a pretty simple use case, but that method would be hugely useful for creating a new object, and receiving it's firebase reference in a promise so I can continue to edit it, or call `$bindto`, instead of having to use the native js library.

**Comment by jwngr** [comment]
Hey there, thanks for using AngularFire and filing this issue!

`$update()` was indeed removed when `$firebase` was removed. The [migration guide](https://www.firebase.com/docs/web/libraries/angular/guide/migration-guides.html) has some examples of how to convert from using `$firebase` to using the core Firebase library, which is the recommended solution here. There is no example for `$update()` explicitly, but the concept is the same.

If you want to update an instance of `$firebaseObject`, you don't even need to call `$firebase.$update()` or use the core Firebase library's `update()` method. All you need to do is something like this:

```
var obj = $firebaseObject(ref);
obj.$loaded().then(function() {
  obj.foo = "bar";
  obj.baz = true;
  return obj.$save();
}).then(function() {
  console.log("Object saved!");
}).catch(function(error) {
  console.log("Error:", error);
});
```

Since the synced object is really just a regular JavaScript object, treat it as such and update it directly. Then, when you want those changes synced to Firebase, just call `$save()`.

**Comment by premiumFrye** [comment]
Thanks for the quick response Jacob, but the reason I'm trying to use something like `$update()` (or `$set()` for my use case, even ) is to avoid calling `$loaded`. My use case is creating a user with a unique id I specify (`fbUrl.com/user/:userid`). With the method proscribed above the entire object at /user is then synced/downloaded, if I'm understanding that correctly--a hugely unnecessary use of bandwidth for saving a user.

**Comment by katowulf** [comment]
In which case you should avoid AngularFire entirely--a great bindings library for handling complexities of syncing objects and arrays into Angular, but entirely unnecessary for a simple write op. As the migration guide already linked suggests, just work directly on the Firebase reference:

    ref.update( newUserData );

However, as you've stated that you are creating a new user with a unique ID, update() is entirely the wrong approach. Instead, to create a new user, you should be utilizing `ref.set()`

Cheers,
Kato

**Comment by jwngr** [comment]
Also, just to add on to what Kato mentioned, if your concern is not downloading the data, you don't want to use `$firebaseObject` at all. Even if you don't call `$loaded()`, instantiating a synced object with `$firebaseObject` will download the data. The `$loaded()` method is just convenience method which will fire once the data is downloaded. If you don't use it, the same things still happen in the background.

So that is why it is better in your case to follow Kato's advice and not use `$firebaseObject` at all but just use the regular Firebase client. Hope that helps!

**Comment by premiumFrye** [comment]
Gotcha--understand much better now why it would actually be a bad idea to
implement `$update`  (or `$set`). I am in fact implementing plain JS client
to just do the write op--makes more sense for my use case now. Thanks for
the reply!
