### ISSUE TITLE
Calling $unauth triggers $onAuth callback with valid authData

### ISSUE THREAD

**Issue by henry74** [firebase/angularfire#601]
I'm doing the following as recommended:
```
var ref = new Firebase("https://****.firebaseio.com/");
var auth = $firebaseAuth(ref);
var offAuth;

this.onAuth = function(loginCallback) {
  offAuth = auth.$onAuth(function() {
    // ...
  });
}

this.logoff = function() {
  auth.$unauth();
  offAuth();
}
```
But I'm noticing the $unauth() is triggering the onAuth callback (as documented) but authData is not null, but instead has valid data in it.  The documentation for AngularFire says:

"Unauthenticates a Firebase client. This method should be called when you want to log out the current user. It takes no arguments and returns no value. When logout is called, the $onAuth() callback(s) will be fired."

So it's not clear if it's supposed to have data or should have authData set to null.  I assumed null, because the firebase unauth() documentation states:

"Unauthenticates a Firebase reference which had previously been authenticated. When a client is unauthenticated, all callbacks attached via onAuth() will fire with a value of null."

Can you clarify what is the expected value for authData when the onAuth callback is fired due to calling $unauth on the $firebaseAuth reference?

Thanks,
Henry

**Comment by katowulf** [comment]
It should call onAuth() with null. Please provide a working repro of this issue. Be sure to include version info.

**Comment by henry74** [comment]
Is there a sample firebase project to use since it requires authentication and logoff?

**Comment by henry74** [comment]
@katowulf I think I might be seeing a race condition where a prior auth check is being done after $unauth has already been called, but not yet completed.  I think I could avoid this through the use of promises, but $unauth doesn't return a promise, right?

**Comment by henry74** [comment]
Going to close this as it is returning null and the problem is due to a race condition in my own code.  Thanks @katowulf

**Comment by jwngr** [comment]
Glad you got to the bottom of this @henry74! I just wanted to answer your open questions for completeness.

> Is there a sample firebase project to use since it requires authentication and logoff?

Sorry we didn't get back to you sooner on this one. It should be pretty straightforward to include the Firebase and AngularFire script tags on a Plunker or CodePen. From there, authentication and logoff are already only a few lines, so I'm not sure a pre-built example is that useful. I'm sure there are examples littered throughout previous GitHub issues though.

> `$unauth()` doesn't return a promise, right?

That is correct. `$unauth()` does not return a promise since it is a synchronous event and takes place immediately.

Let us know if you have other questions!
