### ISSUE TITLE
Publish Nightly / Per Commit Releases

### ISSUE THREAD

**Issue by jamestalmage** [firebase/angularfire#614]
Travis already has a number of utilities for automatically uploading to S3 (some of these may be dated):
 * [artifacts addon](http://docs.travis-ci.com/user/uploading-artifacts/)
 * [artifacts script](http://blog.travis-ci.com/2012-12-18-travis-artifacts/)
 * [deploy addon](http://docs.travis-ci.com/user/deployment/s3/)

I would like to see every build publish four artifacts:
 1. `http://<host>/<bucket>/<commit-hash>.js` - debug build for specific commit
 2. `http://<host>/<bucket>/<commit-hash>.min.js` - minified build for specific commit
 3. `http://<host>/<bucket>/<branch-name>.js` - debug build for latest passing commit on given branch
 4. `http://<host>/<bucket>/<branch-name>.min.js` - debug build for latest passing commit on given branch

I haven't been tracking how stable the `e2e` tests have been lately, but if they are still finicky then maybe our definition of "passing" should just be whether or not the unit tests passed.

**Comment by jwngr** [comment]
Thanks for the suggestion @jamestalmage. I do see the utility in having nightly AngularFire builds, but ultimately, we are pretty strapped for resources at the moment and I doubt this kind of thing will get implemented any time soon. I see the Travis addons are pretty simple, but we would want ones that plug into GCS rather than S3 and I'm not sure there is enough frequent commits to this repo to warrant the added process / complexity. We are actually currently looking to reduce our operation overhead, and I'm afraid this will just make things more complex. Please feel free to convince me of the benefits of doing this though. Have you tried this with other projects? What do you like about it?

**Comment by jamestalmage** [comment]
What I want is an easy way to point my project at a commit or PR that fixes my issues and keep developing. 

It would also be good to give people an easy way to create plunks demonstrating their problem against master (or a way to quickly edit their plunk to point at master) - that way we can confirm the problem is fixed on master simply by refreshing the plunk.

Using browserify would solve this issue in a different way. For people using browserify for their own project, build artifacts become irrelevant; You can just point `package.json` at an url for a specific commit or branch and it gets packaged up by browserify as part of your own build process. I have done this before (pointed a project to one of my own PR's against MockFirebase until such time it was merged and released). It is a really simple solution that does not require you to store custom builds of your dependencies in version control, or change your build in any way. It's just a one line change to `package.json` that jumps right out at you every time you look at the file, gently reminding you that you are not using a current release. 

A GCS solution would not be very hard to do (the command line utility for GCS is pretty robust, it could probably all be done in a shell script no travis plugin needed).

As I think about it, the Travis solution will only work for PR's that are merged or committed directly to `firebase/angularfire` by a collaborator (builds for un-merged PR's would not have access to the S3 / GCS credentials).

I'm not married to the idea.

**Comment by katowulf** [comment]
James, I've looked over a couple ways that I could implement this and decided that I'm not interested in attempting it. All have some degree of setup difficulty and that discourages me because there will be inevitable upgrade issues, downtime troubleshooting, et al. 

We're very focused on reducing our OSS overhead right now so we can focus on quality repos. Perhaps when we reclaim some of that bandwidth, issues like this could be revisited. I'll ponder this for some of the upcoming strategy discussions and see if there is a way it could be added to the overarching build process.

Cheers,
Kato
