### ISSUE TITLE
authWithOAuthToken and facebook plugin error

### ISSUE THREAD

**Issue by mapeveri** [firebase/angularfire#644]
Hi everyone, I find myself developing app with Cordova and AngularFire. In addition, i use plugins cordova for login with google and facebook (https://github.com/Wizcorp/phonegap-facebook-plugin). With google find ok, but facebook displaying this error:
"Invalid authentication credentials provided"

Searching in google, find thats problem is the token, but debugging the app, get token of facebook ok.

Any idea what could it be?

My code:

         facebookConnectPlugin.login(['public_profile'], function(status) {				
			facebookConnectPlugin.getAccessToken(function(token) {
				var auth = AuthFirebase.getFirebaseAuthObj();
	            auth.$authWithOAuthToken(provider, token).then(function(authData, error) {
					//......
				}).catch(function(error) {
					switch (error.code) {
						case 'USER_CANCELLED':
							break;
						default:
							sweetAlert("Error", error, "error");
							break;
					}	

				    $location.path("/");
				});

		  	}),
			function(error) {
				sweetAlert("Error", JSON.stringify(error), "error");
			};
		},function(error) {
			sweetAlert("Error", JSON.stringify(error), "error");
		});

Thanks so much.

**Comment by katowulf** [comment]
At what point in the process is the error message produced?

**Comment by mapeveri** [comment]
Hi @katowulf  the problem is in this line:

auth.$authWithOAuthToken(provider, token).then(function(authData, error) {

**Comment by jwngr** [comment]
If there is a bug here, it is in the Firebase client itself, not AngularFire. That being said, we can still help you get to the bottom of this. I've got some questions for you:
 1. How did you verify that the Facebook token you got was correct?
 2. Have you properly configured your Facebook application by following [the Firebase docs](https://www.firebase.com/docs/web/guide/login/facebook.html#section-configure)?
 3. Have you tried just using Firebase to get the Facebook token instead of using the Facebook connect plugin? You can read about using Facebook with Ionic [here](https://www.firebase.com/docs/web/libraries/ionic/guide.html#section-user-authentication).

**Comment by mapeveri** [comment]
Hi @jwngr ok perfect.

1. Facebook plugin ruturn the accessToken, i understand that is correct.
2. I understand that this is also good, because the login is correct. But here, it's a little different from what the documentation says, that I do on android and not on web.
3. This helps me to call the native Facebook application?. I want call to the application native of facebook, instead of a pop up the web.

Thanks :+1:

**Comment by mapeveri** [comment]
@jwngr Thanks to your response and your points, i verified all my settings and the problem was that he had set bad the APP_ID and the APP_SECRET of facebook on my dashboard firebase.

Now it works well :)
