### ISSUE TITLE
ERROR in example $getRecord(key)

### ISSUE THREAD

**Issue by sosnovskyas** [firebase/angularfire#650]
if we look at the documentation (https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-firebasearray-getrecordkey) the examples use function $getRecord(key) so see
```
var list = $firebaseArray(ref);
var rec = list.$getRecord("foo"); // record with $id === "foo" or null
```
BUT it's not work

this implementation that works
```
var list = $firebaseArray(ref);
list.$loaded()
    .then(function (arr) 
    {
        console.log(arr.$getRecord(_id)); 
    });
```

**Comment by katowulf** [comment]
Thanks for this. I'll see what we can do to clear that up. 

The assumption here is that you'd already have the list loaded if you know a key you want to get out of it (otherwise, where did the key come from?). If you're trying to load a single record, you don't need $firebaseArray(); you can reference the record directly and load it into $firebaseObject.

Furthermore, $loaded() is generally only useful as a debugging tool, so we try not to include it in the examples because it tends to confuse things more than help. We do [cover asynchronous ops](https://www.firebase.com/docs/web/libraries/angular/guide/intro-to-angularfire.html#section-async-intro) and a bit on debugging (i.e. using $loaded()) in the guide.

Again, appreciate the feedback and I'll ponder this.
