### ISSUE TITLE
Need to update bower dependency to Firebase 2.3

### ISSUE THREAD

**Issue by douglascorrea** [firebase/angularfire#653]
For using the new features announced today (Multi-location, deep-paths, etc) we should use firebase 2.3, but angularfire is requiring the 2.2.x

**Comment by jwngr** [comment]
Thanks for this reminder. We will get it updated shortly. We've got lots of repos to update! I'm thinking we should be safe to update the Firebase dependency to `2.x.x` across the board since we own the Firebase client and can ensure that we follow semver and won't make any backwards-incompatible changes in the `2.x.x` versions. That will prevent us from having to update a dozen repos every time we cut a new minor version of the Firebase client.

**Comment by jwngr** [comment]
FYI that [Firebase 1.1.3](https://github.com/firebase/angularfire/releases/tag/v1.1.3) has been released with an updated Firebase dependency.

**Comment by douglascorrea** [comment]
Thank you @jwngr !
