### ISSUE TITLE
Set key with $firebaseArray.$add()

### ISSUE THREAD

**Issue by jaufgang** [firebase/angularfire#672]
In certain places, I would like to be able to specify the key when using $firebaseArray.$add().  I think it would be handy to have the ability to do this added to the function.

I can think of 2 different ways to allow this, either adding an $id property to the data being added and have that used as the key, or alternately calling $add(dataObject, key).  Either one of these approaches would default to the existing behaviour if no key was specified, so this change would not break any existing code.

Is this something that could be added?  I could make the change and create a pull request if it would be accepted.

**Comment by jwngr** [comment]
Thanks for the feature suggestion. We actually have heard this one before, although I can't pull up the past issue. In general, I would say that if you need to specify the key, you should probably be using `$firebaseObject` instead of `$firebaseArray`. Would you mind explaining your use case and we can see if `$firebaseObject` is more appropriate?

**Comment by katowulf** [comment]
Also, adding a record with a specific key can be done as follows: 'firebaseArray.$ref().child( newKey ).set(newData);'

**Comment by jaufgang** [comment]
ok, thanks katowulf, I will use that suggestion,

jwngr, I definitely want to use $firebaseArray, not $firebaseObject.  One reason for wanting to do this is to use single character strings as keys for arrays whose values may be changing very frequently, in order to minimize data transfer.  Each update of a value contains the path as part of the message sent to the client, so keeping the path length as short as possible can make a potentially meaningful difference over a very large number of updates.

**Comment by katowulf** [comment]
I'm not sure $firebaseArray or $firebaseObject make any difference in the efficiency of downloading frequently changing data. Generally speaking, use array for collections, use object for key/value pairs and records. If you run into performance issues or bandwidth concerns, deal with those later (usually by reducing the amount of information you monitor).

**Comment by gerhardcit** [comment]
@katowulf firebaseArray.$ref().child(newKey ).set(newData); does not work does it?
```Uncaught TypeError: memberWhatsNewList.$ref(...).child is not a function```
Is there another way to do this. Having a master list of items (for a eg: group) and then adding that to a member requires this technique. 
One often wants to add to an array specified your own key (for small lists)
Any suggestions otherwise please?

**Comment by jwngr** [comment]
This original thread is almost a year and a half old. Please start a new topic. And since this is a usage question, it is better suited for [Stack Overflow](https://stackoverflow.com/questions/tagged/firebase) or the [Firebase Google Group](https://groups.google.com/forum/#!forum/firebase-talk). Please re-post on one of those forums? Please also remember to include version information and a code sample (if relevant) to help us resolve your issue.

**Comment by gerhardcit** [comment]
@jwngr , yes, old topic, but still outstanding in my view. And not so much a usage issue as a feature that is missing on the $firebaseArray. If the Firebase guys thinks is is never going to be addressed, then fine, but it seems like a very simple feature missing on the array handling.

No point in asking Stack Overflow, it either gets solved here at the core, or we live without it and hack our way around it.

**Comment by jwngr** [comment]
This question was initially asked on October 27, 2015, when the API was versioned as `1.x.x`, not `2.x.x` as it currently is. So, it is not surprising that code samples for the legacy version of this library do not work with the current version.

We'd be happy to help you out if you start a new thread on [Stack Overflow](https://stackoverflow.com/questions/tagged/firebase) or the [Firebase Google Group](https://groups.google.com/forum/#!forum/firebase-talk).
