### ISSUE TITLE
Problem with successive 'child_added' and 'child_changed' events with $firebaseArray

### ISSUE THREAD

**Issue by brentahiti** [firebase/angularfire#677]
When adding a child and then updating it right away, execution is as follows:

1 - firebaseArray.$$added(snap, prevChild) => https://github.com/firebase/angularfire/blob/master/src/FirebaseArray.js#L634

2 - firebaseArray.$getRecord($firebaseUtils.getKey(snap)) (which returns null and doesn't call the $$process function as a result) => https://github.com/firebase/angularfire/blob/master/src/FirebaseArray.js#L639

3 - firebaseArray.$$process('child_added', rec, prevChild) => https://github.com/firebase/angularfire/blob/master/src/FirebaseArray.js#L635

Is this an intended behavior?

**Comment by katowulf** [comment]
Please provide a smallish repro demonstrating the behavior, with some steps to run it.

**Comment by brentahiti** [comment]
Made this plunkr http://plnkr.co/edit/Ca5y5SPUQsJprIiFHfXN

Hope it reproduces the behavior on your side. The item is added but not updated in the array. But it is indeed created in the database, if you refresh you'll see the data appear

**Comment by sivaramsi** [comment]
I too suffer from the same issue , could you guys give a fix ASAP.

**Comment by katowulf** [comment]
Presumably, this is the expected output? Not seeing any issues.

![image](https://cloud.githubusercontent.com/assets/959972/11675511/950f0882-9de7-11e5-9392-29627477dff1.png)

**Comment by jwngr** [comment]
Kato, try clicking the "Add" button. You'll see that `foo -` shows up without any `bar`. If you refresh the page, everything shows up as `foo - bar` once again.

**Comment by katowulf** [comment]
Hrm. Indeed. It does work, however, if one moves the update() callback inside of the push completion callback: http://plnkr.co/edit/xwS1ba5TJBDARBTMCSkt?p=preview. 

It also works when calling $add() instead of dropping to the API to use push(): http://plnkr.co/edit/IVKP2GVTte99jkYcn63Q?p=preview

So this begs the question: What is the use case where I would be updating a record which hasn't triggered a completion callback yet, and also would not go ahead and put the data into the push() function, instead of making two calls? 

I'm guessing this is simplified for consumption, and it's not that straightforward, so it may help to understand the underlying use case in order to see what sort of importance this has and what a good test case would look like.

**Comment by sivaramsi** [comment]
Am developing a product management tool in which there comes a scenario
where am creating a milestone with set of tasks , while creating milestone
all the tasks that are in that milestone will be updated with the current
milestoneid (pushid) .after created am fetching sets of tasks for the
that milestone by using orderby query ..at those time i couldnt get the
data

**Comment by katowulf** [comment]
I can't grok that. Can you make a repro that demonstrates that behavior? And before you bother, can it not be fixed by simply moving the updates into the completion callback? Does it have to be done outside the completion callback for some reason?

**Comment by sivaramsi** [comment]
That worked :)

**Comment by katowulf** [comment]
I'm going to mark this won't fix, because it feels like a pretty distant edge case. There's probably something here that could be improved, but I had a brief look through the code and fixing it seemed like it would add layers of complexity to the code for little benefit.  If anybody runs into a use case that can't easily be solved with the above, ping this ticket with a strong argument and we'll reopen.

**Comment by brentahiti** [comment]
The use case is happening server side. We push an object in a queue and some other logic updates it later on (using the ref returned by the push). There's some processing happening in between so we can't do it altogether. It usually does it fast enough so that it fires consecutive 'child_added' and 'child_changed' events. We want to avoid using delays in order for this to work

**Comment by katowulf** [comment]
This isn't a server-related bug. This repro occurs when push() and update() are called on the client without waiting for the callbacks to complete, because of latency compensation, and would not be affected by remote updates.

For your server-side issue, you might try not returning the ref until the push callback is triggered. Use promises or callbacks.
