### ISSUE TITLE
Load order issues with SystemJS

### ISSUE THREAD

**Issue by blackxored** [firebase/angularfire#681]
Apparently there seems to be something wrong with the use of globals in both the bower and the npm versions, since recently started giving load order issues due to use of the `angular` global.
As a workaround I managed to "shim" it with:

```
jspm install npm:angularfire -o '{"shim": {"dist/angularfire": {"deps": ["angular"]}}}'
```

Let me know if you can see a proper and cleaner solution here. Thanks.

**Comment by jwngr** [comment]
I am not familiar with SystemJS and I'm not sure exactly what we need to do to support it. If you know what is needed and it doesn't break out compatibility with the myriad of other JS loaders out there, we'll gladly review and merge. Otherwise, it may be a while until we get a chance to look at SystemJS / we may wait until more people start complaining about it.

**Comment by jwngr** [comment]
Closing as "won't fix" for now. I'm not familiar with SystemJS and we've heard of no other complaints about issues with it. If you put together a PR with a fix, we will gladly review and merge it in. Otherwise, this issue will stay closed until we hear more chatter about this.
