### ISSUE TITLE
ui-sortable with 2 firebaseArray models

### ISSUE THREAD

**Issue by mastef** [firebase/angularfire#687]
Hey there, so as mentioned in https://github.com/firebase/angularfire/issues/200 and https://github.com/angular-ui/ui-sortable/issues/421 using ui.sortable with firebaseArray currently is a bit messy, since the latter relies on .splice to move an array value from one ng-model to another ng-model, which doesn't get synced when used with a firebaseArray.

The use case is using multiple ui.sortable lists and to be able to move one item from one list, to another list. E.g. to easily create similar functionality to Trello, or other PM boards. Currently if I drag & drop an item from ng-model1 to ng-model2, then firebase gets out of sync, since the arrays have been spliced in that operation.

The current work-around that works for me is an ui-sortable.js override, which isn't so pretty. See the 2nd revision of this gist https://gist.github.com/mastef/0ae8ba7595cafad2c85f/revisions?diff=unified ( the first revision is the sortable.js itself, the 2nd revision are the $firebaseArray necessary changes )

2 reasons why this is not a nice work-around : It overrides ui-sortable to solely work with $firebaseArrays, so it won't work with normal arrays any longer, and secondly it hacks the core script.

Explanation of the edit : 

https://gist.github.com/mastef/0ae8ba7595cafad2c85f/revisions?diff=unified#diff-639d008ea3358a52bf08d13ea75bbd58L280

We pick up an item in a list and drop it on another ng-model.
What happens in the code : Locate the item in the old model through `$getRecord`, save it in a temporary internal var and remove it from the old list.

https://gist.github.com/mastef/0ae8ba7595cafad2c85f/revisions?diff=unified#diff-639d008ea3358a52bf08d13ea75bbd58L228

We drop the item on another list, so we a) find out if there's an item located at the drop offset of the new list. If yes, we drop the current item with a smaller priority than the item we dropped it over.

If not, we assume that we dropped at the end of the list. Dropping temporary item with a maximum priority of 99999.

And b) finally we add the item with the new priority to the new ng-model.

https://gist.github.com/mastef/0ae8ba7595cafad2c85f/revisions?diff=unified#diff-639d008ea3358a52bf08d13ea75bbd58R277

Last but not least we recalculate priorities on each list change based on current index offset.

So this works very specifically with $firebaseArray and ui.sortable + multiple lists. Another way to achieve this would be to override the .splice, etc functions for $firebaseArray. But @katowulf I suppose you would know more about the issues this approach would come with.

**Comment by katowulf** [comment]
Okay, so the following factory will essentially give you what you want. It's a checkpoint/save strategy, which will allow splice to be used freely on the synchronized array, and then, when `saveChanges()` is called, it determines what has changed in the array and makes appropriate updates.

```
app.factory('CheckpointArray', function($firebaseArray) {
  return $firebaseArray.$extend({
    checkpoint: function() {
      this._checkpointIds = this._buildIds();
    },

    saveChanges: function() {
      if (!this._checkpointIds) {
        throw new Error('No checkpoint declared. Can\'t save yet. You may need to wait until $loaded() completes.');
      }
      var oldIds = this._checkpointIds;
      var currentIds = this._buildIds();
      var recs = this.$list;
      var ref = this.$ref();
      
      this._checkpointIds = null;
      
      //console.log('oldIds', oldIds);
      //console.log('currentIds', currentIds);
      
      // look for removed records
      angular.forEach(oldIds, function(pos, key) {
        if (!currentIds.hasOwnProperty(key)) {
          //console.log('removed', key);
          ref.child(key).remove();
          delete this._indexCache[key];
        }
      }, this);
      
      // look for moved or added records
      angular.forEach(currentIds, function(pos, key) {
        var rec = this.$list[pos];
        if (pos !== oldIds[key] || pos !== rec.$priority) {
          //console.log('saving', rec.$id, oldIds[key], pos, rec.$priority);
          rec.$priority = pos;
          this._indexCache[key] = pos;
          this.$save(rec);
        }
      }, this);
    },

    _buildIds: function() {
      var ids = {};
      var ref = this.$ref();
      angular.forEach(this.$list, function(rec, i) {
        // to simplify prioritizing and moving things around
        // assign all records an id right away, even if they
        // have not been saved to the server before
        // they will be added when calling saveChanges()
        if (!rec.$id) {
          rec.$id = ref.push().key();
        }
        ids[rec.$id] = i;
      });
      return ids;
    }
  });
});
```

[Here's a working proof](https://jsfiddle.net/katowulf/1dfyz2rq/) of the factory. This should work fine with any sortable or drag drop tool which uses splice to modify the contents. The process for using the factory is:

   - call `checkpoint()` when you are going to hand off the array to ui-sortable or another service using splice()
   - let the service make its updates
   - when they are completed, call `saveChanges()` (and probably checkpoint() again) to apply the differences

There are a couple non-intuitive but critical things here that wouldn't be easy to figure out without knowing the internal workings of AngularFire--things I'll keep in mind while we work on the Angular 2 design.

1) Use Firebase.remove() instead of $remove, since the element doesn't exist in the array and therefore $remove would ignore the request.

2) Give every record added to the array a push id, rather than calling $add for similar reasons. 

3) Update all the priorities to match the array ordering, so drag and drop and reordering work as expected.

3) Update `this._indexCache` any time we do the manual add/removes described in 1) and 2). This keeps the cached list of ids > array positions up to date.

**Comment by mastef** [comment]
Oh @katowulf this is amazing! This factory would still require to call `saveChanges()` everytime after a splice, pop, shift, unshift and split operation right?

Any thoughts on extending the prototype methods instead to call `saveChanges()` after the original method has run? ( I suppose you fiddled with this for a few more years than I did to see if such an approach would be actually sane :D )

This could even turn into a semi-official implementation of how to handle $firebaseArray's with all the array functionalities in place. Any huge limitations that you can see with this approach?

**Comment by katowulf** [comment]
I fiddled with a few different ideas. This is really the best approach. Trying to save after each individual splice or op gets a bit schizophrenic (keep in mind we're getting changes from the server, too, so you're essentially trying to send data two directions through the same pipe).

It's also hard to tell when to actually perform the save without knowing all the details of the implementation. For example, when you splice a record out, should it be immediately removed? To move a record, you first splice it out and then put it in a different location (ideally that would trigger child_moved rather than child_removed and child_added).

Thus, a checkpoint/save is the most sane, as you suspected. If you want to automate this in some way, I'd try a [debounce](https://davidwalsh.name/javascript-debounce-function) on saveChanges() that has a liberal pause.

**Comment by mastef** [comment]
Again, thank you @katowulf for your time on this - this is very valuable in working with Sortable Javascript Arrays in Angular and Firebase!

**Comment by douwevdijk** [comment]
Absolutely fantastic! Have been working around this issue for months. Thanks!
