### ISSUE TITLE
github oauth popup not centered

### ISSUE THREAD

**Issue by GavinPalmer1984** [firebase/angularfire#700]
![angularfire](https://cloud.githubusercontent.com/assets/5564129/13143222/07991476-d608-11e5-8d91-a93f7a609156.gif)

**Comment by jwngr** [comment]
Gahh, looks like GitHub has updated the styling on their login page! Thanks for reporting this. Technically, this is a problem with the underlying Firebase SDK, not AngularFire, so I'm going to close the issue here and move it into our internal bug tracker. We are putting together a fix for the Firebase client and will plan to get it released ASAP. Keep an eye out for a 2.4.1 release of the Firebase SDK in the coming days. I'll try to remember to ping here when it gets released.

**Comment by jwngr** [comment]
FYI that 2.4.1 was just release with a fix for this. Happy Friday!

https://www.firebase.com/docs/web/changelog.html

**Comment by GavinPalmer1984** [comment]
Thanks @jwngr 

> 
> Hi Gavin!
> 
> It would be nice if you guys had a condensed responsive version of the sign
> in and sign up pages for people who use Github for oauth in a popup on
> their website. Thanks!
> 
> I appreciate you writing in about this! I can see how this would be really useful and how the GitHub OAuth popup can be improved. Though it's not currently possible to implement this right now, I've added it to our internal Feature Request List for our team to see.
> 
> All the best,
> GitHub Staff

**Comment by jwngr** [comment]
Thanks for reporting this to GitHub themselves. A responsive sign up page would be super useful and most other OAuth providers already have it. Hopefully they get it added sometime soon!
