### ISSUE TITLE
Angularfire re-exports itself as 'firebase' without first requiring vanilla firebase as a dependency

### ISSUE THREAD

**Issue by zakdances** [firebase/angularfire#707]
I was just about to create a pull request for this, but I want to get your feedback on how to proceed:

Angularfire needs firebase as a dependency (It's even listed as such in [package.json](https://github.com/firebase/angularfire/blob/master/package.json)). But it's *not* listed as such in the [Angularfire module definition](https://github.com/firebase/angularfire/blob/master/index.js):

```
require('./dist/angularfire');
module.exports = 'firebase';
```
What I was expecting was something like

```
require('firebase');
require('./dist/angularfire');
module.exports = 'firebase';
```

Instead, it appears that Angularfire is re-exporting without referencing vanilla firebase. Is there an intentional design purpose here that I'm missing? I try to investigate further:

But you've [completely obfuscated firebase.js](https://github.com/firebase/firebase-bower/blob/master/firebase.js), presumably to protect yourself from competitors? That's interesting...I haven't seen that technique done since I was browsing old Java projects on Sourceforge. Since I've apparently hit the proprietary "No Fly Zone", can you let me know if there's a recommended way to get Angularfire to work with module loaders? Or is installing and importing `firebase` AND `angularfire` manually the only way?

**Comment by jwngr** [comment]
@bendrucker can probably provide some context here since he introduced this change with https://github.com/firebase/angularfire/pull/567.

Also, you can find a non-minified version of the Firebase client on our CDN [here](https://cdn.firebase.com/js/client/2.4.2/firebase-debug.js).

**Comment by bendrucker** [comment]
Does AngularFire actually call `Firebase`? I thought the lib expected a reference. In that case a peerDep is correct, not a regular dep.

**Comment by jwngr** [comment]
Yeah, I actually also mentioned that myself. I've already made `firebase` a peer dep with some of our other repos (e.g. [ReactFire](https://github.com/firebase/reactfire/blob/df2e9998efa8e3fc0291c2387c8266ab61a3f409/package.json#L32), [GeoFire](https://github.com/firebase/geofire-js/blob/c7cbdab0a8543f57c3b9709eda7c9e7b676e9854/package.json#L31)) and we should probably do the same here.

**Comment by bendrucker** [comment]
Yup, peer would be correct here. The code is fine.

**Comment by zakdances** [comment]
> Does AngularFire actually call Firebase?

Maybe I'm missing something, but this

>  refs[key] = new Firebase(value);

is in [`firebaseRef`](https://github.com/firebase/angularfire/blob/master/src/firebaseRef.js). Where is the `Firebase` class being defined in not `firebase.js`?

Actually, it looks like you're correct because (when I try to use `.child()` in my own code) I'm getting this error:

`TypeError: $firebaseRef.child is not a function`

So apparently `$firebaseRef` is not really a `new Firebase` replacemenet, it's a "Firebase-lite" with only partial feature support? I'm just trying to understand the purpose here.

Firebase does stuff that Angularfire objects still can't, like vivify object trees. So `firebase.js` still needs to be installed/imported for me. It'd be nice if `$firebaseRef` was a first class citizen!

**Comment by bendrucker** [comment]
Since it's being used as an implicit global there Firebase should indeed get the same treatment as Angular. The index file is incorrect as is w/ the addition of `$firebaseRef`.

Another option is to require the user to supply a constructor to Angular's DI via `module.value('Firebase', Firebase)` and then AngularFire can inject it for `$firebaseRef` eliminating the implicit global. 

The latter is the best solution in theory but a breaking change relative to the current release.

**Comment by jwngr** [comment]
Hmm yeah I guess I haven't been following this repo close enough to realize that we now directly use `Firebase` as a global with the addition of `$firebaseRef`. Seems obvious in retrospect though.

Thanks for the feedback, Ben. I think updating the index file is probably the best course of action at this point to avoid a breaking change. Especially with Angular 2 / AngularFire 2 on the horizon.

+@davideast who added the `$firebaseRef` stuff.

**Comment by bendrucker** [comment]
Yup, changing the index is a good move. Angular and Firebase should both be listed in `dependencies`.

**Comment by katowulf** [comment]
Would using $window.Firebase solve the global issue? Are there other nuances I'm missing after a quick scan of this thread? This is my fault for missing the new global during code review; I'll handle if we have a consensus on the best answer.

**Comment by bendrucker** [comment]
> Would using `$window.Firebase` solve the global issue?

Not really, that just allows you to mock the dependency w/ Angular's test tools. `$window` is still an implicit global dep read via an explicit syntax.

The idea here is:

1. CommonJS users are already supported via the `index.js` file
2. That support comes in the same form of the hack I originally convinced the Angular team to adopt.
3. It works because both Angular and Firebase always attach themselves to the global scope and have ecosystems that expect the same. You can `require` the index file and then be guaranteed that the global will be available to the files the index file requires.

I'll send a PR.
