### ISSUE TITLE
Upgrade to the Firebase 3.x.x SDK

### ISSUE THREAD

**Issue by FabVillegas** [firebase/angularfire#718]
I'm just reading the web API reference, but what about integrating angular?

**Comment by javier-lerones-gallego** [comment]
I just imported one of my projects to the new console and the web app still works fine with firebase 2.4.2 and angularfire 1.2.0. I will test upgrading firebase to 3.0.0 later today and see if it breaks.

**Comment by Kesymaru** [comment]
ok, so you can import your project on the console, what about the support for firebase 2, the docs for the 2 versions appears as deprecated so i would like to know for how long this version will be supported because i am just finishing an app and is not cool to release a new app that uses a deprecated firebase version.

**Comment by FabVillegas** [comment]
Upgrading to Firebase 3.0.0 modifies some of the sintaxis to save and read data, besides the use of the Firebase reference and child events.

You can import the database to the new console and most of the queries are done the same way.
But with Fireabse 3 you have to use firebase.database(), and it sure affects this library right?
I would also assume $firebaseRef no longer works with version 3.

**Comment by BenDz** [comment]
Interesting, on Firebase migration guide, they are talking about Angularfire 2.x to support Firebase 3.x: https://firebase.google.com/support/guides/firebase-web#update_your_firebase_libraries_numbered

But it looks like this Angularfire 2.x doesn't exist yet.

**Comment by javier-lerones-gallego** [comment]
You are correct, 1.2.0 $firebaseRef no longer works with firebase 3.0.0. I cannot even authenticate after upgrading.

```
ReferenceError: Firebase is not defined
    at FirebaseRef.$$createMultipleRefs [as $$createRefsFromUrlConfig] 
```

**Comment by javier-lerones-gallego** [comment]
[Angular fire 1.xx to 2.xx guide](https://github.com/firebase/angularfire/blob/2.0/docs/migration/1XX-to-2XX.md)

It is in the 2.0 branch docs folder

**Comment by jwngr** [comment]
Okay, lots of different discussions going on here. Let's see if I can set things straight.

We are upgrading this AngularFire library (compatible with Angular 1.x) to the new 3.0.0 Firebase SDK in #717. We will be following semver and release it as version `2.0.0` since it contains breaking changes (the auth stuff, not the database stuff). This does not imply that it will work with Angular 2.

If you want to use AngularFire in Angular 2, check out [AngularFire2](https://github.com/angular/angularfire2). It will be upgraded to the Firebase 3.0.0 in the coming days to weeks. @davideast and @jeffbcross are leading the AngularFire2 effort.

The existing AngularFire library (and all Firebase apps) will continue to work if you simply keep using the libraries you are using today. If you migrate your app to the new console, you existing apps will continue to work. We've worked really hard to ensure backwards compatibility with our existing libraries.

If you do decide to upgrade to the new Firebase JavaScript SDK, there are in fact a handful of breaking changes. Please check out [our migration guide](https://firebase.google.com/support/guides/firebase-web).

**Comment by FabVillegas** [comment]
@jwngr thanks for your time. I really appreciate the effort handling this update. Really, great work.
Are there estimated times for these releases?

**Comment by abehaskins** [comment]
I would suspect in the hours to days timeline - but no promises :)

**Comment by rosswaycaster** [comment]
I noticed that in order to use the new "Sign up confirmation" auth feature you have to be using Firebase SDK 3.0.0 so I'm looking forward to the AngularFire upgrade as well!

**Comment by AdrienDC** [comment]
@abehaskins the firebasearray code update is working pretty well with firebase 3 :)

**Comment by matiishyn** [comment]
Hi.
We've updated Firebase to v3 but our application does not work because all calls to DB are made with AngularFire 1.2 which currently does not support v3. Is it right?

@jwngr could you please give any estimate/date when #717 will be merged (which means the new version of AngularFire will support Firebase v3, right?). I just need to give a report to my client when I can finish migration to Firebase v3.

Thank you

**Comment by jwngr** [comment]
We should be able to review, test, merge, and publish a new version by the end of next week. Hopefully sooner. In the meantime, please continue with the existing libraries against the `2.x.x` Firebase SDKs.

**Comment by Yongde1109** [comment]
@jwngr Thanks Jacob! Really appreciate your hard work!

**Comment by xDarp** [comment]
what we want? Merge!, when we want? Now! Thx your guys for the hard work.

**Comment by jwngr** [comment]
To give an update here: @abehaskins and I are fighting with some test failures and trying to make sure the library works as expected with the `3.x.x` SDK. This lib is a bit trickier to update than the other *Fire libs since the code is old, there are more tests, and it uses more parts of the underlying Firebase SDK (like auth). Hang tight and hopefully we can get a new version out to you sometime this week.

**Comment by jwngr** [comment]
The [new version](https://github.com/firebase/angularfire/releases/tag/v2.0.0) of AngularFire which is compatible with the Firebase `3.x.x` SDK is out! 🎉
