### ISSUE TITLE
How to convert Base64 to URL?

### ISSUE THREAD

**Issue by amanuel2** [firebase/angularfire#727]
Yea i already asked this in stackoverflow:
http://stackoverflow.com/questions/37482260/convert-base64-to-url

But since the users there are not expierenced with firebase i thought i would ask the creators. Well my question is i have this base64 i am putting to firebase as you can see in my service here:

https://github.com/amanuel2/ng-forum/blob/master/services/encodeImageToBase64.js

. Well storing a base64 as you might guess really "destroys" the database , and also when i have to load it, it "eats" performance.. Is there a way around this? Thankyou.

**Comment by dreadjr** [comment]
You might want to check out firebase's new storage api.

**Comment by amanuel2** [comment]
@dreadjr .. Im not using Firebase SDK 3.0.0 ... im using the previous one, 2.3.3 i think, its in my github anways

**Comment by katowulf** [comment]
This is in no way related to AngularFire and Stack Overflow is the correct place for this question. Upgrading to 3.x and taking advantage of Storage is definietly the way to go (still not related to AngularFire and not going to be added here; use the SDK directly). Uploads in 2.x have been discussed ad nauseam, so I'll point you to those threads rather than re-hash them here.

how to: http://stackoverflow.com/questions/13955813/how-can-i-view-and-store-images-in-firebase/13957446#1395744
best practices: https://groups.google.com/forum/#!searchin/firebase-talk/upload/firebase-talk/Vff1-Ix6y8o/BgPt73FdCAAJ
using 64 bit encoding: https://groups.google.com/forum/#!searchin/firebase-talk/upload/firebase-talk/vKcycr9LqfM/ZVgfYzOdWbUJ
uploading images to hosting: https://groups.google.com/forum/#!searchin/firebase-talk/upload/firebase-talk/g2ddtIn1cO8/x_FeHlrU5_oJ

More on Stack Overflow:
http://stackoverflow.com/questions/13955813/how-can-i-view-and-store-images-in-firebase/13957446#13957446
http://stackoverflow.com/questions/13955813/how-can-i-view-and-store-images-in-firebase
http://stackoverflow.com/questions/24521969/handling-user-images-on-firebase
http://stackoverflow.com/questions/33914339/how-to-upload-image-files-using-firebase
http://stackoverflow.com/questions/18044703/storing-retreiving-dataimage-in-firebase-very-slow

I hope that helps!
☼, Kato
