### ISSUE TITLE
$firebaseAuth().$getAuth().provider = null

### ISSUE THREAD

**Issue by armensg** [firebase/angularfire#772]
In the new angularifre; whats the correct method to get the auth provider? I tried providerId but this seems to return 'firebase'. Is that the provider for 'email' sign in?

**Comment by iRoachie** [comment]
`$firebaseAuth.$getAuth().providerData` returns an array of providers since some apps can have multiple providers. If you only have email just get the first object in the array.

The object looks like this.

<img width="187" alt="screen shot 2016-06-09 at 6 12 09 am" src="https://cloud.githubusercontent.com/assets/5962998/15926276/25c3fbd8-2e09-11e6-846b-e50134466cc8.png">

**Comment by sirgalleto** [comment]
I have the same error `$firebaseAuth.$getAuth is not a function`.

**Comment by iRoachie** [comment]
`$firebaseAuth` is a function. Refer to the docs before submitting issues. 

```js
app.controller("MyAuthCtrl", ["$scope", "$firebaseAuth",
  function($scope, $firebaseAuth) {
    // Get the auth object
    $scope.authObj = $firebaseAuth();

    //Get the user
    var firebaseUser = $scope.authObj.$getAuth();
  }
]);

```

[View docs here](https://github.com/firebase/angularfire/blob/master/docs/reference.md#firebaseauth)

**Comment by sirgalleto** [comment]
Ohh @iRoachie very thanks.
