### ISSUE TITLE
$firebaseAuth().$getAuth()= null when browser refresh after a successful login

### ISSUE THREAD

**Issue by ghorkov** [firebase/angularfire#777]
Hi,

**Angular: 1.4.8**
**Firebase: 3.0.2**
**AngularFire: 2.0.1**

BTW I'm upgrading from Firebase 2.4.2 / AngularFire 1.1.3 and this feature was working correctly before.

### Steps to reproduce
I'm able to successfully login with Google or Anonymous and retrieve the user data. Just after login I can call `$firebaseAuth().$getAuth()` and I can get a JSON object that contains the AuthData with `{"credential": {...}, "user": {...}}`

The problem arises when I do a browser refresh. My initial code will call `$firebaseAuth().$getAuth()` to retrieve the user data in case the user has logged in already but it returns `null` every time.

I've also tried calling: `firebase.auth().currentUser` but it also comes back as `null`

### Expected behavior
For `$firebaseAuth().$getAuth()` to get the AuthData of the current user

### Actual behavior
`$firebaseAuth().$getAuth()= null ` even when the user has login successfully

**Comment by iRoachie** [comment]
`$getAuth()` is a **synchronous call** to get the current user details, however the nature of angularfire is asynchronous, so by the time that `$getAuth()` is called it is usually before the page loads completely. So it returns null.

A better solution explained in the docs is to use the `$onAuthStateChanged()` callback to watch for changes on the auth object. This is a much more reliable way of getting the user since it's a listener and will only return when the event actually takes place.

```js
$scope.authObj.$onAuthStateChanged(function(firebaseUser) {
  if (firebaseUser) {
    console.log("Signed in as:", firebaseUser.uid);
  } else {
    console.log("Signed out");
  }
});
```

Check it out [here.](https://github.com/firebase/angularfire/blob/master/docs/reference.md#onauthstatechangedcallback-context)

**Comment by ghorkov** [comment]
Thanks iRoachie!

I'm now able to get the logged in user using `$onAuthStateChanged`.

As a side note: On AngularFire 1.1.3 I was using a **synchronous call**  with `$firebaseAuth(ref).$getAuth()` and it was working correctly.
