### ISSUE TITLE
$ref() returns query object

### ISSUE THREAD

**Issue by grosem** [firebase/angularfire#780]
### Version info

**Angular:** 1.5.6

**Firebase:** 3.0.4

**AngularFire:** 2.0.1

### Test case

```
var query = $firebaseRef.child("items").orderByChild("sth");
$firebaseArray(query).$loaded().then(function(items) {
  console.log(items.$ref().key);
});
```

### Expected behavior

Get firebase reference and its key.

### Actual behavior

`$ref()` returns the query object (and not the reference) if the `$firebaseArray` was initiated with a query. Therefore, you need to call `items.$ref().ref.key` to access the key.

**Comment by iRoachie** [comment]
Currently `$firebaseRef` isn't supported at the moment as theirs no mention of it in the docs. We get the ref from the global firebase object `firebase.database.ref()`. Then apply child or orderBy modifiers.

Here's a pen I made just for this question. You only need to call `$ref().key` on the array.

**Comment by grosem** [comment]
@iRoachie, thanks for your comment. I do not think it is related to the $firebaseRef provider as this is a simple wrapper. Your pen does not use an `orderByChild` query - if you change it to something like this: `firebase.database().ref().child('news').orderByChild('category');`, you will notice that `$ref()` returns a Query object.

**Comment by jwngr** [comment]
Thanks for logging the issue @grosem. I'm not 100% certain what the expected behavior is here. We will need to do some digging and see if this behavior changed with the `3.x.x` release. I don't think it did though. It seems useful to be able to get back the original query you created a `$firebaseArray` with, so this may be "works as intended".

@katowulf should be able to let us know for sure.

**Comment by grosem** [comment]
I would be happy if you do not change it - just a note in the docs would be great.

**Comment by jwngr** [comment]
Cool, I definitely agree we should note that in the docs if that is indeed the intended behavior. We will do some digging and leave this issue open to handle updating the docs. Thanks!

**Comment by katowulf** [comment]
It looks like this is the historical behavior. [1](https://github.com/firebase/angularfire/blob/504383dd3734ba8509dfac72268ce862e9e5a273/src/FirebaseArray.js#L113) [2](https://github.com/firebase/angularfire/blob/504383dd3734ba8509dfac72268ce862e9e5a273/src/FirebaseArray.js#L240)

It seemed like the right choice, since there's no way to recover the original query if we don't provide it here. It is annoying for some operations.
