### ISSUE TITLE
How to Evade $digest errors. 

### ISSUE THREAD

**Issue by amanuel2** [firebase/angularfire#781]
### Version info

**Angular:** Latest AngularJS 1 version

**Firebase:** Firebase 2.4.2

**AngularFire:** Latest AngularFire for above firebase version

**Other (e.g. Node, browser, operating system) (if applicable):**

### Test case

This is a concept question. No Plnk,fiddle,etc needed
### Steps to reproduce

# $digest Errors

Im sure everyone has encountered the very famous $digest error:

Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []

Well, that happenes when you have a lot of $firebaseObject, and $firebaseArray and you call the $loaded function many times. Well, obviously for big projects like forums you will need a lot of those. Is there any way i can pass this problem? Thankyou for your time, right now we are codintg this at cloud9 so if we could discuss there also it would be awesome! https://ide.c9.io/amanuel2/ng-fourm

**Comment by iRoachie** [comment]
I've never came across any digest errors using angularfire. Not sure if your problem is happening because you're using Angularfire 2.0.4 with Firebase 2.4.2. The current version of angularfire is really to be used with the new version of firebase(3). As so the api methods changed.

**Comment by amanuel2** [comment]
@iRoachie I Use AngularFire 1.2.0

**Comment by iRoachie** [comment]
If you could replicate this it in a plunkr or so would be great. But i've never dealt with that problem even using older versions of firebase and angular. Digest loops usually happen when a change on a model triggers a digest cycle and that one triggers another one etc. This is usually a problem with personal code, and the framework.

**Comment by amanuel2** [comment]
The thing is @iRoachie i cant... we can work on it [here](https://ide.c9.io/amanuel2/ng-fourm) though.

**Comment by jwngr** [comment]
Thanks for opening the issue. Unfortunately, I think this issue is a bit too vague at the moment. I'm not really sure AngularFire is the issue here and without a reliable repro in JSFiddle or Plunker, this is not actionable for us. I know you linked to Cloud 9, but I've never used it before and having to create an account just to see whatever is behind the sign-in screen is not something I'm going to do right now.

As for the use of `$loaded()`, you really should not need to use it very often unless you are debugging. In general, you should just create your `$firebaseArray` and `$firebaseObject` instances and show the data as it shows up, not try to process it once it is initially loaded. There are valid use cases for it, but using it a lot in your app is an anti-pattern.

**Comment by amanuel2** [comment]
@jwngr so i dont have to do $loaded.... wow man, i misconfused firebase. Sorry sir
