### ISSUE TITLE
$firebaseStorage and fir-storage-src proposal

### ISSUE THREAD

**Issue by davideast** [firebase/angularfire#785]
@jwngr @katowulf @abehaskins 

This issue addresses two features
- `$firebaseStorage()` service
- `fir-storage-src` directive
## $firebaseStorage

Here is my proposal for the `$firebaseStorage()` API, written in TypeScript:

You'll notice that is follows the same binding convention as `$firebaseObject()`, and `$firebaseArray()`, as both of those services take a database reference. `$firebaseStorage()` is similar but it takes a storage reference. 

The piece of feedback I'm most looking for is surrounding the events for the `$put()` method. I've currently wrapped each function of the `state_change` event into a method, `$progress`, `$error`, and `$completed`.

``` ts
interface $firebaseStorage {
  (ref: firebase.storage.Reference): FirebaseStorage;
}

interface FirebaseStorage {
  new (storageRef: firebase.storage.Reference);
  $put(File): UploadTask;
  $getDownloadURL(): Promise<string>;
  $getMetadata(): Promise<Object>;
  $updateMetadata(): Promise<Object>;
}

interface UploadTask {
  $progress: (Object) => (); // Can't be a promise
  $error: (Error) => (); // Should this be a promise?
  $complete: (Object) => (); // Should this be a promise?
}
```

Here it is in action:

``` js
function MyCtrl($firebaseStorage) {
  // Create a reference (possible create a provider) 
  const storageRef = firebase.storage().ref('user/1.png');
  // Create the storage binding
  const storageFire = $firebaseStorage(storageRef);

  // Get the possible download URL
  storageFire.$getDownloadURL().then(url => {

  });

  const file = // get a file;
  // upload the file
  const task = userImage.$put(file);
  // monitor progress state
  task.$progress(metadata => console.log(metadata));
  // log a possible error
  task.$error(error => console.error(error));
  // log when the upload completes
  task.$completed(metadata => console.log(metadata.downloadURL));

  // meta data
  storageFire.$getMetadata(metadata => console.log(metadata)); 
  storageFire.$uploadMetadata({
    cacheControl: 'public,max-age=300',
    contentType: 'image/jpeg'
  });
}
```
## fir-storage-src

To make displaying images from Firebase Storage simple and adhere to the security model I recommend we develop a directive that retrieve's the download url and set's the `src` attribute of the image:

``` html
<!-- no interpolation -->
<img fir-storage-src="users/1.png" />

<!-- interpolation -->
<img fir-storage-src"users/{{currentUser.uid}}.png" />
```

[If you're interested in seeing this in action, I've written a demo app here.](https://flexchat.firebaseapp.com)

**Comment by davidrensh** [comment]
Hi David, could it be possible to upload flexchat src into github? Kind of fans have human rights?

**Comment by davideast** [comment]
No problem @davidrensh! I've been developing it on github since the beginning.

https://github.com/davideast/flex-chat

**Comment by abehaskins** [comment]
Can you expand a bit on how you would `const file = // get a file;` in angular? If this is complex we might consider including this as part of the service or as a directive somehow.

**Comment by davideast** [comment]
@abehaskins Yes, this is not trivial. I think we could include a small `FileUploadDirective`. Which would work like this:

```html
<file-upload on-change="$ctrl.myChangeCallback">
    My Upload Label
</file-upload>
```

And the code works a bit like this:

```
function FileUploadDirective() {
  return {
    restrict: 'E',
    transclude: true,
    scope: {
      onChange: '='
    },
    template: `
      <input type="file" name="file" id="firebase-storage-file-upload" class="inputfile" />
      <label for="firebase-storage-file-upload"><ng-transclude></ng-transclude></label>
    `,
    link: function (scope, element, attrs) {
      element.bind('change', function () {
        scope.onChange(Array.from(element.children().files));
      });
    }
  }
}

const app = angular.module('app');
app.directive('file-upload', FileUploadDirective);
```

**Comment by abehaskins** [comment]
*Sorry this isn't as nice as David's proposal.*

What if we also made a `FirebaseStorageFile` directive and a `$firebaseStorageFile` service  (not convinced this is idiomatic, but just an idea)

It might look like...

```html
<input 
  type="file" 
  firebase-storage-file="/photos/goat.png" 
  ng-model="fileRef"  />

<button 
  ng-click="fileRef.$put()">
  Upload
</button>
```

I imagine  `$firebaseStorageFile` to be a lot like `$firebaseStorage` except...

It is initialized with a storage ref or a `$firebaseStorage` instance. At initialization it fetches the blob data from the URL and makes it accessible via `$getData()`.
```js
var fileRef = new $firebaseStorageFile(storageRef.child("photos/goat.png"));

// Pass fileRef.$getData() around for raw data
// ...or use fileRef.$getDownloadUrl() for img tags
```

Local data can be changed via `$setData()`  (this is what our `FirebaseFile` directive will call) which influences `$getData()` and `$getDownloadUrl()` but does not upload to Firebase Storage until `$put()` is called.

```js
var fileRef = new $firebaseStorageFile(storageRef.child("photos/goat.png"));
var url;

// Initial load of URL uses Firebase Storage public URL
url = $fileRef.$getDownloadUrl();

// User selects new file
$fileRef.$setData(NEW_FILE)

// Gets reader.readAsUrl() i.e. base64 version for local previews and such
url = $fileRef.$getDownloadUrl();

// Save to Firebase Storage
$fileRef.$put();

// Gets public Firebase Storage URL
url = $fileRef.$getDownloadUrl();
```

If `put()` is called without arguments it uploaded the data from `$setData()` if it's called with with a new file it will act the same as the underlying Storage ref and call `$setData()` locally.

We can easily do things like `loaded()` with a `$firebaseStorageFile()` since we'll be loading it on init then all future loads will likely be cached we can help users display loading prompts and such.

I think adding this would give developers a lot of power to interact directly with files with minimal code. It's definitely a simpler path for them with the underlying services still exposed if they need more control.

Thoughts?

**Comment by CyrusZei** [comment]
any ETA if this will be added  to the angularfire ?

**Comment by davideast** [comment]
@CyrusZei Still hashing out a good solution. 

I'm starting to wonder if even AngularFire is the best spot for Firebase Storage. Should this functionality live as it's own module? Not everyone will need storage support and you can build the Firebase SDK without storage included to save kbs.

Thoughts?

**Comment by CyrusZei** [comment]
well, my thoughts I think that it would be great if there was one module that had all the functions that firebase offers instead of adding more modules and keep track of two modules.

**Comment by davideast** [comment]
While one module is easy, it adds extra and possibly unneeded size to the library. This size is an extra burden over the networks making the page load of a site slower. Using a standard convention it should be easy to include the needed modules.

```js
const app = angular.module('app', ['firebase' ,'firebase.storage']);
``

**Comment by CyrusZei** [comment]
yes, I was more thinking about version control ?, but I understand what you mean

**Comment by davideast** [comment]
I think I have a solution that makes everyone happy. We need to start breaking out functionality into specific modules for library size, but we could still expose the `"firebase"` module for convenience.

If you want individual modules:

```js
const app = angular.module('app', ['angularfire.auth', 'angularfire.database', 'angularfire.storage']);
```

If you want everything

```js
const app = angular.module('app', ['firebase']);
```

Thoughts?

**Comment by CyrusZei** [comment]
that is really great thought! I like that alot

**Comment by katowulf** [comment]
The determining factors for whether they share a repo or get their own should be:

  1. Do they have a lot of overlapping code? Will splitting them result in redundancy? (maybe, see below)
  2. Are they always used together, such that separating them simply means two install steps? (maybe, see below)
  3. Are they logically the same thing? (not really)
  4. Is the project of sufficient scope and size to bother splitting them because of testing or code management? (not really)
  5. Are they likely to diverge in the future? (not really)

Client library size could be managed by simply creating optimized releases as part of a build process. This shouldn't really a big factor in whether they are included together.

One thing to consider is that Auth is needed by both Storage and Database. Storage also has an optional dependency on Database (It's likely meta data would be stored in the database since Storage can't list, track, categorize, or store meta in any way itself.). 

We could also argue that Auth indirectly needs Database, since we have the same issue as Storage--it can't independently store meta data, lists, or any useful organization of users.

So the logical dependency arrangement in my mind looks something like this:

![image](https://cloud.githubusercontent.com/assets/959972/16391055/41a28bbc-3c5a-11e6-85d9-df39de18e028.png)

Given this, my though is that would should ideally include them together. If that seems impractical because of difficulty managing them as one entity, or because of testing or other real-world constraints, then Auth and Database should remain AngularFire and Storage should be considered as a "pluggable module" for the lib and maintained separately.

**Comment by katowulf** [comment]
@davideast at the Angular/module level, yes, definitely do this.

**Comment by davideast** [comment]
@katowulf Agreed. They still belong in the same repository, but different modules are now needed with the 3.0 SDK changes.

I opened up an issue to address this specifically as to not detract from the Storage spec discussion.

#799

**Comment by 32xnabin** [comment]
when is AngularFire 3.0.0 being released? can I surely expect storage referece wrapped in it?

**Comment by jdnichollsc** [comment]
+1

**Comment by Goowaz3** [comment]
?

2016-08-21 4:59 GMT-03:00 Juan David Nicholls Cardona <
notifications@github.com>:

**Comment by tianweiliu** [comment]
I ported firebase storage upload example(https://firebase.google.com/docs/storage/web/upload-files) to a factory:
https://gist.github.com/tianweiliu/6594f6cc09d0e5a3ef6c704db6d2f97a

**Comment by soumak77** [comment]
@davideast @abehaskins any resolution on whether a file upload directive will be added?  I started playing with the changes in #865 and quickly realized I'll need that type of directive.  I'd like to hear any plans on this feature before I start to building my own directives.

**Comment by jwngr** [comment]
Just as a note to those following along on this thread: @davideast is going to be putting together docs for the new Storage features and, once those are ready, we will cut a `2.3.0` release. Give us a little bit more time before we can get this into your hands.

**Comment by jdnichollsc** [comment]
I ported other example of the firebase storage upload https://gist.github.com/jdnichollsc/5ddc40c1c482e6209a8f4d634fd11d1e 

Regards, Nicholls

**Comment by dfjs** [comment]
AngularFire 2.3.0 has now been released, which includes `$firebaseStorage`:

https://github.com/firebase/angularfire/blob/master/docs/reference.md#firebasestorage
