### ISSUE TITLE
Modify returned auth 'catch' errors.

### ISSUE THREAD

**Issue by uloga** [firebase/angularfire#806]
I can't seem to find anything on how to modify returned auth errors e.g: 'Firebase.authWithPassword failed: First argument must contain the key "email" with type "string" into custom error message? 

```
.catch(function(error){
       
       // console.log(error); is returning string only 
         
});
```

**Comment by jwngr** [comment]
Closing since this does not follow our issue template. Please create a new issue.

Note that the error you are getting is a developer error, not a user error, which is why you are just getting a string error message. I would suggest making sure you are using the latest version of the library and do what the error message suggests.
