### ISSUE TITLE
Installing angularfire through JSPM gives error

### ISSUE THREAD

**Issue by SamarRizvi** [firebase/angularfire#857]
Running `jspm install angularfire` gives error: `no version match for github:firebase/firebase-bower@3.x.x`

**Comment by jwngr** [comment]
I've never used `jspm` and have no idea how it works. Can you provide some more details about what we would need to do here? The latest versions of both AngularFire and Firebase are on Bower so I'm not sure why it doesn't work.

**Comment by SamarRizvi** [comment]
I you use ^3.0.0 instead of 3.x.x, it shall work fine on JSPM. JSPM probably doesn't understand 3.x.x.

**Comment by jwngr** [comment]
Seems like a bug on their end to be honest. `3.x.x` is valid semver. I'd raise the issue with their project if you haven't already.

**Comment by kmturley** [comment]
I believe this is because your package.json does not contain the correct version:
https://github.com/firebase/angularfire/blob/master/package.json

    "version": "0.0.0",

I forked the angularfire repo, and changed the package version:
https://github.com/kmturley/angularfire/commit/2514e3646f1adec27bbd2579909eb557b5884f59

    "version": "2.3.0",

Then ran the installation pointing to my fork instead:

    jspm install github:kmturley/angularfire

And it worked!
