### ISSUE TITLE
Error with 2.X firebase library: firebase is not defined

### ISSUE THREAD

**Issue by JimTheMan** [firebase/angularfire#860]
### Version info

**Angular:** 1.4.2

**Firebase:** "2.0.2"

**AngularFire:** 1.1.4

**Other (e.g. Node, browser, operating system) (if applicable):**

### Test case

This repo, master branch: https://github.com/ng-nj/ng-nj.org

### Steps to reproduce

npm i, bower i, gulp serve (should show the error):

![ngnjorg](https://cloud.githubusercontent.com/assets/5354163/19188657/32dbb8c2-8c61-11e6-9236-a0b3dd5748ca.png)

### Expected behavior

To successfully call the *firebase* global var and not to show an error.

### Actual behavior

Showing an error....

**Comment by JimTheMan** [comment]
sigh. I guess firebase 2.X is just unstable. This is honestly driving me crazy, and it seems like there is no fix. A black eye for firebase. :'(

**Comment by JimTheMan** [comment]
I also get this error when installing firebase via npm:

![ng-nj_org_ _gulp_nvm_rc_version__term_program_apple_terminal_ _127x37_and_ngnjorg_and_authentication_service_js_-_ng-nj_org_-____g_ng-nj_org_](https://cloud.githubusercontent.com/assets/5354163/19196546/00e264ce-8c84-11e6-9293-9d6e09758b01.gif)

**Comment by jwngr** [comment]
Thank you for following the issue template.

You are including AngularFire `1.x.x` which works with Firebase `2.x.x`, but you are using the API for Firebase `3.x.x`. This definitely will not work and it is expected to throw errors since your dependencies are out of date. Try upgrading to the latest AngularFire `2.x.x` and Firebase `3.x.x` SDKs instead. Starting with our [quickstart](https://github.com/firebase/angularfire/blob/master/docs/quickstart.md) should explain how to get started with AngularFire.

Note that Firebase `2.x.x` creates a `Firebase` (capital "F") global while Firebase `3.x.x` creates a `firebase` (lowercase "f") global. This is the error you are getting, although more things will be broken even after you change the global's name. You should just use the latest versions and hopefully things will work for you.

**Comment by JimTheMan** [comment]
Ok thanks. I wanted to use the firebase storage service with the 2.x sdk.
Is this not possible?

**Comment by jwngr** [comment]
The Storage service was added in Firebase `3.x.x`, so you cannot use it with the `2.x.x` SDK.

**Comment by JimTheMan** [comment]
Ohhhh. Wow that clears up a lot of confusion. Lol
