### ISSUE TITLE
firebaseUtils deepCopy treating Date object as a common object

### ISSUE THREAD

**Issue by henriquesobral** [firebase/angularfire#878]
In firebaseUtils module ```src/utils/utils.js```, ```deepCopy``` function, the first line check if a property is not an object and return it, if isn't. But, a Date is a object that not be treated as an array or an regular object "{}", and must returned in the first line as well a simple value is.

**Update:** ```stripDollarPrefixedKeys``` function have the same problem.

### Version info

**Angular:** 1.5.3

**Firebase:** 3.5.3

**AngularFire:** 2.1.0

### Test case

http://jsfiddle.net/2e6syt5k/2/

**Comment by katowulf** [comment]
Please resubmit and follow the issue template. Also, include reasoning on why this is a problem. Date format conversions and storage techniques are proprietary and vary wildly. Unclear why utils.js should be expected to handle this.

**Comment by jwngr** [comment]
This seems like an actual bug to me and I think @henriquesobral provided a good repro for us to work with. Our `$firebaseUtils.deepCopy()` method should be able to handle `Date` objects and I don't think it's that hard for us to support. I'm re-opening this issue.

What @katowulf is alluding to though is that `Date` objects are rarely what you want to store in the Firebase Realtime Database since Firebase itself does not handle them (e.g. do `ref.set(new Date())` and you'll see what I mean). You are better off storing timestamps generated from a `Date` object in Firebase instead of the `Date` object itself.

That being said, our utils function should still behave properly.

**Comment by jwngr** [comment]
We would gladly accept a PR for this if you want to give it a shot!

**Comment by katowulf** [comment]
Yep, I was confused here : ( Thanks for kicking the soup Nazi out of the kitchen!

**Comment by henriquesobral** [comment]
First, sorry about late reply, I don't know why, but I'm not receiving any update emails from Github.
Second, sorry about my English, it's not my native language.

What I'm trying to explain, is that ```deepCopy``` function cannot treat JS Date object as a regular JS Object, iterating over and copying properties. 
I'm using ```$bindTo``` to make 3-way databind and I have a Date field (type=date) in my form and in my model. So I'm pointing ```ng-model``` to a function that treat my Date before saves it, but because ```$bindTo``` uses ```deepCopy```, my function always receives an empty Object instead a JS Date.

Function in ```$firebaseObject.$extend``` binded on form used to treat JS Date:
```javascript
getterSetterBirthday: function (value) {
  if (arguments.length) {
    tempDate.setTime(this.personalInfo.birthday = value.getTime());
  } else {
    tempDate.setTime(this.personalInfo.birthday);
  }
  return tempDate;
}
```

The adjustments that I made on utils.js to make my app works, first to the first line of ```deepCopy``` function:

**before:** 
```javascript
if( !angular.isObject(obj) ) { return obj; }
```
**after:** 
```javascript
if( !angular.isObject(obj) || angular.isDate(obj) ) { return obj; }
```

and to the first line of ```stripDollarPrefixedKeys``` function:

**before:** 
```javascript
if( !angular.isObject(data) ) { return data; }
```
**after:** 
```javascript
if( !angular.isObject(data) || angular.isDate(data) ) { return data; }
```
