### ISSUE TITLE
Child data stored as array when syncing with Ang-fire, but gets retrieved as object when data added externally.

### ISSUE THREAD

**Issue by paotoya757** [firebase/angularfire#885]
Hello,

To explain my problem, I start out with an object X in angular. This object X has an array, and once I store it in Firebase, and modify it through Angular-Fire, this array will continue to be an array data type. Nevertheless, when I add to this array from a NodeJS client (using firebase api), and doing a push(), the syncing loads X's array as an OBJECT type.

**Object[0]'s data was only modified using angular-fire $add**
![image](https://cloud.githubusercontent.com/assets/7131457/20740919/e86335be-b694-11e6-9746-84e5c3a261d4.png)

**On the other hand, Object[3]'s data was modified doing a push() from nodeJS with the firebase JS api. Note that Angular fire loads it as an OBJECT type ando not an ARRAY type.** 
![image](https://cloud.githubusercontent.com/assets/7131457/20740962/2aa92686-b695-11e6-85cb-48fb7cd70951.png)

**Take into account that once this error happens, other stuff that where tightlty binded with ARRAYS, will cease to function. E.g CHARTS**

**Comment by jwngr** [comment]
Closing as invalid as it doesn't follow our issue template and doesn't include a minimal repro. Please re-open and follow the issue template.

You may want to check out our [docs on working with lists of data](https://firebase.google.com/docs/database/web/lists-of-data) to read more about how array-coercion works in Firebase. Some of what you mention may be expected behavior.
