### ISSUE TITLE
limitToFirst() does not work with $firebaseArray()

### ISSUE THREAD

**Issue by r3wt** [firebase/angularfire#909]
```js
$scope.featuredListings = $firebaseArray( firebase.database().ref('properties').orderByChild('featured').equalTo(true).limitToFirst(16) );
```

Expected:
only 16 items in array
Actual:
hundreds of items in array

**Comment by katowulf** [comment]
[Working for me](https://jsfiddle.net/katowulf/m6spubtp/).

Note that all issues have to follow the issue template provided. I understand this is asking a lot and is generally annoying when you feel your question is straightforward, but just trust that it's critical to keep things streamlined and manageable for our team. I'm closing this for now because it doesn't adhere to these requirements. Feel free to resubmit according to the template, being absolutely sure to include a working, minimal repro of the problem and version info.

**Comment by jwngr** [comment]
Closing since this does not follow the issue template.

**Comment by r3wt** [comment]
that query in your example is not the same, but nice try. not suprising, you fucking faggot.
