### ISSUE TITLE
firebaseArray is not updating view somehow.

### ISSUE THREAD

**Issue by jrsakizci** [firebase/angularfire#918]
Hello. First of all i want to made a plunkr for this but code is so complex and reproducing this may cost a lots of time. But i am gonna attach pictures about this problem. 

Problem is: Data is coming perfectly from database, and its assigning the data to array but somehow view is not updating.

1-) I have an array of objects. So i used firebaseArray for this. 

This is my first array
![asdasd](https://cloud.githubusercontent.com/assets/7869720/23308828/18391268-fab5-11e6-92fd-92a336548de1.PNG)

![1](https://cloud.githubusercontent.com/assets/7869720/23308720/cb23a164-fab4-11e6-9d1e-61c395856d04.PNG)

![problem](https://cloud.githubusercontent.com/assets/7869720/23308699/b8dfc406-fab4-11e6-8631-3aa957d243ad.PNG)

2-) I am checking data on Console.Log and its coming, its changing.. $timeout, setTimeout doesnt working..

I am new and this is my first project with Firebase&AngularFire. Maybe i did something wrong, maybe i am doing all wrong but i dont know what.. BTW; this is service not controller, i am not/can not using SCOPE.

**Comment by jwngr** [comment]
This is a usage question, which is better suited for [Stack Overflow](https://stackoverflow.com/questions/tagged/firebase) or the [Firebase Google Group](https://groups.google.com/forum/#!forum/firebase-talk). Can you please re-post on one of those forums and paste the link here? Please also remember to include version information and a code sample (if relevant) to help us resolve your issue.

It would be helpful to see how you are using `liveData` in your HTML view. The second block of code you included should not be necessary since `$firebaseArray` handles all of that stuff for you. You should just reference your `liveData` array variable in your view and that's it.

**Comment by jrsakizci** [comment]
@jwngr - First of all thank you for help. Firebase Google Group doesnt showing my question somehow. On stackoverflow no body tells me anything.. I dont know what i am gonna do with that data. 

Its annoying, its just not updating view..
