### ISSUE TITLE
Support Firebase 4.x

### ISSUE THREAD

**Issue by rarkins** [firebase/angularfire#934]
### Version info

**Angular:**

1.x

**Firebase:**

4.x

**AngularFire:**

2.3.0

### Steps to reproduce

Run `npm install` and receive warning:

`WARN angularfire@2.3.0 requires a peer of firebase@3.x.x but none was installed.`

### Expected behavior

angularfire should support Firebase 4.x

### Actual behavior

angularfire does not support Firebase 4.x

**Comment by rarkins** [comment]
@jwngr will this be implemented soon?

**Comment by jwngr** [comment]
I don't work at Firebase / Google anymore so I'm not going to be able to answer that question.

**Comment by rarkins** [comment]
@jwngr do you know who would be best to comment?

**Comment by jwngr** [comment]
@katowulf can probably help out, but I'm not sure since I don't work there anymore.

**Comment by idanen** [comment]
Did you run the tests (or something of your own) with firebase 4?

**Comment by rarkins** [comment]
@idanen I had it running with firebase 4 for a few days and didn't notice problems. But I prefer not to run anything that's "unsupported". I guess Google don't maintain this repository anymore because it's angular.js (v1)

**Comment by rarkins** [comment]
@katowulf could you update us on the status of (a) if Firebase 4.x will be supported here, and (b) is this repository deprecated?

**Comment by cklemming** [comment]
Yesterday marked 3 months since Firebase 4.0 was released.

I'm also a bit surprised the lack of official support for FB 4.x in AngularFire given it's still widely used (or so I presume). Would be great to understand if this library is getting deprecated.

**Comment by idanen** [comment]
I had an issue that happened for me on "production" apps but never locally.
I had plenty of trouble trying to debug it, since it failed in an asynchronous mess...

After plenty of digging, I think the blame is this change:

> CHANGED BREAKING: firebase.auth.Auth.prototype.onAuthStateChanged now triggers on sign in and sign out.

(from [firebase change log](https://firebase.google.com/support/release-notes/js), version 4.0.0)

The method `firebase.auth.Auth.prototype.onAuthStateChanged` **does not** trigger for changed auth token anymore. 
So I think the simple solution for AngularFire would be to use the new [`firebase.auth.Auth.prototype.onIdTokenChanged`](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onIdTokenChanged) which behaves the same as the "old" `onAuthStateChanged`.

I'll try it out when I'll find the time to test it.

**Comment by idanen** [comment]
Ok, so the problem was not with `onAuthStateChanged` or any athoe Firebase or AngularFire code.

The issue I had happens because of an issue with uglifying firebase 4 and above.

See discussions:
https://github.com/firebase/firebase-js-sdk/issues/154
https://github.com/PolymerLabs/polybuild/issues/27
https://github.com/PolymerLabs/polyclean/issues/4

**Comment by dylanjha** [comment]
@rarkins I'm looking in at the source code here. This package specifies `"firebase": "3.x.x"` as both a "dependency" and a "peerDependency". See here: https://github.com/firebase/angularfire/blob/master/package.json#L29-L34

Despite this, I don't think this library actually loads firebase itself. I can't find anywhere in the angularfire source code where 'firebase' get's required.

In your project, if you specify `"firebase": "^4.6.1" and run `yarn install` (or `npm install`) then two versions of firebase will be installed:

* `node_modules/firebase (v4.6.1)`
* `node_modules/angularfire/node_modules/firebase (v3.6.1)` 

Even though the 3.6.1 version gets installed, I don't think it actually gets used. All the interfaces into `angularfire` get passed a firebase ref and if that ref is created from the Firebase 4.6 SDK everything seems to work as expected.

Perhaps someone from angularfire (@katowulf, maybe?) could confirm this or correct me if I'm wrong here, the main question being:

* If I am using `firebase: "^4.6.2"` as a dependency in my package.json, and I am using angularfire, **Does angularfire load it's own version of firebase or does it just use the one that I am using?**

**Comment by vuk-nikolic** [comment]
Any news for supporting firebase 4.x?

**Comment by 625alex** [comment]
Also looking for support of Firebase 4.

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg
